### ISSUE TITLE
error at line => var dtype = torch.@float;

### ISSUE THREAD

**Issue by Cyberduke01** [SciSharp/Torch.NET#7]
I have installed both Torch.net and PyTorch and I am current trying to run the example code given. 

I however get the following error at this line "var dtype = torch.@float;":

System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (0x8007000B)
  Source=Python.Runtime
  StackTrace:
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Torch.torch.InstallAndImport(Boolean force)
   at Torch.torch.<>c.<.cctor>b__313_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Torch.torch.get_self()
   at Torch.torch.get_float()

**Comment by henon** [comment]
This to me looks like a 64bit vs 32bit problem. Something doesn't match.
